import {useEffect,useRef,useState,type ReactNode} from 'react';
import './sensor-dossier.css';
type Session={token:string;user:{role:string}};
type Person={id:string;name:string;email:string;role:string;active:boolean};
type Account={id:string;name:string;owner_name:string|null};
type Condo={id:string;name:string;account_id:string|null};
type Dossier={sensor:{sensor_id:string;serial:string;sensor_type:string;central_serial:string|null;active:boolean;account_id:string|null;account_name:string|null;owner_user_id:string|null;owner_name:string|null;responsible_user_id:string|null;responsible_name:string|null;unit_id:string|null;unit_identifier:string|null;resident_name:string|null;building_name:string|null;condominium_name:string|null;last_seen_at:string|null;last_reading_at:string|null;claimed_at:string|null;claimed_by_name:string|null;created_at:string;conversion_factor:number;counter_digits:number;max_flow_m3_hour:number|null;last_raw_value:number|null;virtual_counter:number;needs_review:boolean};users:Person[];audit:{id:string;created_at:string;action:string;actor_name:string|null;actor_role:string|null;payload:unknown}[];permissions:{manage:boolean;transfer_account:boolean;change_owner:boolean;manage_unit:boolean}};
const base=import.meta.env.DEV?(import.meta.env.VITE_API_URL??'http://localhost:3000').replace(/\/$/,''):'';
async function api<T>(path:string,s:Session,init?:RequestInit):Promise<T>{const r=await fetch(base+path,{...init,headers:{authorization:`Bearer ${s.token}`,'content-type':'application/json'}});const b=await r.json();if(!r.ok)throw new Error(b.error??'Não foi possível concluir');return b;}
const date=(s:string|null)=>s?new Date(s).toLocaleString('pt-BR'):'Não registrado';
const number=(v:number|null)=>v===null?'Não configurado':new Intl.NumberFormat('pt-BR',{maximumFractionDigits:9}).format(Number(v));
const labels:Record<string,string>={sensor_account_transferred:'Conta proprietária alterada',sensor_responsible_changed:'Responsável pelo sensor alterado',unit_responsible_changed:'Responsável pela unidade alterado',account_owner_changed:'Proprietário da conta alterado',install:'Sensor instalado / transferido',remove_installation:'Instalação encerrada',claim:'Equipamento vinculado',meter_reading_adjustment:'Leitura conferida',update:'Configuração alterada',retire:'Sensor desativado'};
export function SensorDossier({s,id,onClose,onChanged,children}:{s:Session;id:string;onClose:()=>void;onChanged:()=>void;children:ReactNode}){
  const dialog=useRef<HTMLDialogElement>(null),[data,setData]=useState<Dossier|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('overview'),[revision,setRevision]=useState(0),[action,setAction]=useState(''),[value,setValue]=useState(''),[reason,setReason]=useState(''),[accounts,setAccounts]=useState<Account[]>([]),[members,setMembers]=useState<Person[]>([]),[condos,setCondos]=useState<Condo[]>([]),[condo,setCondo]=useState(''),[ready,setReady]=useState(false),[notice,setNotice]=useState('');
  useEffect(()=>{const previous=document.activeElement as HTMLElement|null;dialog.current?.showModal();return()=>previous?.focus()},[]);
  useEffect(()=>{let alive=true;const controller=new AbortController();void api<Dossier>(`/api/v1/sensores/${id}/ficha`,s,{signal:controller.signal}).then(d=>{if(alive){setData(d);setError('')}}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false;controller.abort()}},[id,s.token,revision]);
  useEffect(()=>{if(!action||!data)return;let alive=true;setReady(false);setError('');const load=async()=>{
    try{if(action==='account'||action==='condo'){const [a,c]=await Promise.all([api<Account[]>('/api/v1/gestao/contas',s),action==='condo'?api<Condo[]>('/api/v1/condominios',s):Promise.resolve([])]);if(alive){setAccounts(a);setCondos(c.filter(x=>!x.account_id))}}
      if(action==='owner'){const m=await api<Person[]>(`/api/v1/gestao/contas/${data.sensor.account_id}/membros`,s);if(alive)setMembers(m)}
      if(alive)setReady(true);
    }catch(e){if(alive)setError(e instanceof Error?e.message:'Falha ao carregar opções')}};void load();return()=>{alive=false};
  },[action,id,s.token]);
  function open(next:string){setNotice('');setAction(next);setValue(next==='responsible'?data?.sensor.responsible_user_id??'':next==='unit'?data?.sensor.resident_name??'':'');setReason('');setCondo('');setError('')}
  async function save(){if(!data)return;setBusy(true);setError('');try{
    const sensor=data.sensor;
    const path=action==='owner'?`/api/v1/gestao/contas/${sensor.account_id}/proprietario`:action==='condo'?`/api/v1/gestao/condominios/${condo}/conta`:`/api/v1/sensores/${id}/${action==='account'?'conta':action==='unit'?'responsavel-unidade':'responsavel'}`;
    const body=action==='owner'?{user_id:value,expected_owner_id:sensor.owner_user_id,reason}:action==='account'?{account_id:value,expected_account_id:sensor.account_id,reason}:action==='condo'?{account_id:value,reason}:action==='unit'?{name:value,reason}:{user_id:value||null,reason};
    await api(path,s,{method:'POST',body:JSON.stringify(body)});setAction('');setNotice('Alteração registrada no histórico.');setRevision(x=>x+1);onChanged();
  }catch(e){setError(e instanceof Error?e.message:'Falha ao salvar')}finally{setBusy(false)}}
  const sensor=data?.sensor;
  return <dialog ref={dialog} className="sensor-dossier" onCancel={e=>{e.preventDefault();if(!busy)onClose()}}><header className="dossier-header"><div><p className="overline">FICHA DO EQUIPAMENTO</p><h2>Sensor {sensor?.serial??'…'}</h2></div><button className="secondary" disabled={busy} onClick={onClose}>Fechar</button></header><div className="dossier-body">{error&&<div className="v2-error" role="alert">{error}</div>}{notice&&<p role="status" className="v2-info">{notice}</p>}{!data&&!error&&<p role="status">Carregando ficha…</p>}{data&&sensor&&<><nav className="dossier-tabs" aria-label="Seções da ficha">{[['overview','Informações'],['history','Leituras e instalações'],...(data.permissions.manage?[['access','Usuários e vínculos'],['audit','Auditoria']]:[])].map(([v,label])=><button key={v} className={tab===v?'primary':'secondary'} onClick={()=>{setTab(v);setAction('')}} disabled={busy}>{label}</button>)}</nav>
    {tab==='overview'&&<><div className="dossier-grid"><section><h3>Propriedade e responsabilidade</h3><dl><dt>Conta proprietária</dt><dd>{sensor.account_name??'Sem conta vinculada'}</dd><dt>Proprietário da conta</dt><dd>{sensor.owner_name??'Não definido'}</dd><dt>Responsável pelo sensor</dt><dd>{sensor.responsible_name??'Não definido'}</dd><dt>Responsável pela unidade</dt><dd>{sensor.resident_name??'Não informado'}</dd></dl></section><section><h3>Instalação</h3><dl><dt>Condomínio</dt><dd>{sensor.condominium_name??'Não instalado'}</dd><dt>Bloco / unidade</dt><dd>{[sensor.building_name,sensor.unit_identifier].filter(Boolean).join(' / ')||'Não instalado'}</dd><dt>Vinculado por</dt><dd>{sensor.claimed_by_name??'Não registrado'}</dd><dt>Data da vinculação</dt><dd>{date(sensor.claimed_at)}</dd></dl></section><section><h3>Medição</h3><dl><dt>Contador bruto</dt><dd>{sensor.last_raw_value===null?'Sem leitura':String(sensor.last_raw_value).padStart(sensor.counter_digits,'0')}</dd><dt>Hidrômetro</dt><dd>{number(sensor.virtual_counter)} m³</dd><dt>Fator de conversão</dt><dd>{number(sensor.conversion_factor)} m³ por incremento</dd><dt>Dígitos / vazão máxima</dt><dd>{sensor.counter_digits} / {number(sensor.max_flow_m3_hour)}{sensor.max_flow_m3_hour!==null?' m³/h':''}</dd></dl></section><section><h3>Comunicação</h3><dl><dt>Equipamento</dt><dd>{sensor.active?'Ativo':'Desativado'} · tipo {sensor.sensor_type}</dd><dt>Central</dt><dd>{sensor.central_serial||'Não informada'}</dd><dt>Última comunicação</dt><dd>{date(sensor.last_seen_at)}</dd><dt>Última leitura aceita</dt><dd>{date(sensor.last_reading_at)}</dd></dl></section></div>{sensor.needs_review&&<p className="v2-info">Medição aguardando conferência. Consulte o hidrômetro físico antes de ajustar a referência.</p>}{data.permissions.manage&&<button className="primary" onClick={()=>setTab('access')}>Gerenciar vínculos</button>}</>}
    {tab==='history'&&children}
    {tab==='access'&&data.permissions.manage&&<><p>O responsável acompanha o equipamento. A conta define a propriedade. Compartilhar acesso é uma operação separada.</p><div className="dossier-actions"><button className="secondary" onClick={()=>open('responsible')} disabled={busy}>Trocar responsável pelo sensor</button>{data.permissions.manage_unit&&<button className="secondary" onClick={()=>open('unit')} disabled={busy}>Editar responsável pela unidade</button>}{data.permissions.transfer_account&&<><button className="secondary" onClick={()=>open('account')} disabled={busy}>{sensor.account_id?'Transferir para outra conta':'Vincular conta proprietária'}</button><button className="secondary" onClick={()=>open('condo')} disabled={busy}>Regularizar condomínio sem conta</button></>}{data.permissions.change_owner&&<button className="secondary" onClick={()=>open('owner')} disabled={busy}>Trocar proprietário da conta</button>}</div>
    {action&&<form className="v2-form dossier-action" onSubmit={e=>{e.preventDefault();void save()}}><h3>{action==='account'?'Conta de destino':action==='owner'?'Novo proprietário da conta':action==='condo'?'Vincular condomínio à conta':action==='unit'?'Responsável pela unidade':'Responsável pelo sensor'}</h3>{action==='account'&&<p className="v2-info">A transferência encerra a instalação atual e remove o responsável, os acessos e os convites pendentes compartilhados diretamente no sensor. Depois, instale-o em uma unidade da nova conta. O histórico anterior será preservado e ficará restrito ao Super Admin nas consultas deste equipamento.</p>}{action==='owner'&&<p className="v2-info">Esta alteração vale para toda a conta e todos os seus equipamentos. O novo proprietário deve ser um administrador ativo já incluído na conta. O anterior mantém seu acesso administrativo até que seja revogado separadamente.</p>}{action==='condo'&&<label>Condomínio sem conta<select required value={condo} onChange={e=>setCondo(e.target.value)}><option value="">Selecione</option>{condos.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}{action==='unit'?<label>Nome do responsável<input maxLength={150} value={value} onChange={e=>setValue(e.target.value)}/></label>:<label>{action==='account'||action==='condo'?'Conta':'Usuário'}<select required={action!=='responsible'} value={value} onChange={e=>setValue(e.target.value)} disabled={!ready}><option value="">{action==='responsible'?'Sem responsável':'Selecione'}</option>{action==='account'||action==='condo'?accounts.filter(a=>action==='condo'||a.id!==sensor.account_id).map(a=><option key={a.id} value={a.id}>{a.name} · {a.owner_name??'Sem proprietário'}</option>):(action==='owner'?members.filter(u=>['admin','superadmin'].includes(u.role)):data.users).filter(u=>u.active).map(u=><option key={u.id} value={u.id}>{u.name} · {u.email}</option>)}</select></label>}<label>Justificativa<textarea minLength={3} maxLength={500} required value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="dossier-actions"><button className="primary" disabled={busy||!ready||reason.trim().length<3}>{busy?'Registrando…':'Confirmar alteração'}</button><button type="button" className="secondary" disabled={busy} onClick={()=>setAction('')}>Cancelar</button></div></form>}
    <h3>Usuários com acesso ao sensor</h3><p className="muted-text">Inclui acessos herdados da conta, condomínio, bloco e unidade. O perfil abaixo é o perfil geral do usuário.</p><div className="table-wrap"><table><thead><tr><th>Usuário</th><th>E-mail</th><th>Perfil geral</th><th>Status</th></tr></thead><tbody>{data.users.map(u=><tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td>{u.role}</td><td>{u.active?'Ativo':'Inativo'}</td></tr>)}</tbody></table></div>{!data.users.length&&<p>Nenhum usuário com vínculo explícito. Super Admins possuem acesso global.</p>}</>}
    {tab==='audit'&&data.permissions.manage&&<><p className="v2-info">Registros protegidos contra edição e exclusão no banco. Correções geram novos registros. Até 100 eventos mais recentes deste sensor e, para gestores da conta, alterações de proprietário.</p>{data.audit.map(e=><article className="dossier-event" key={e.id}><strong>{labels[e.action]??e.action}</strong><p>{date(e.created_at)} · {e.actor_name??'Sistema / não registrado'}{e.actor_role?` (${e.actor_role})`:''}</p><details><summary>Ver dados registrados</summary><pre>{JSON.stringify(e.payload,null,2)}</pre></details></article>)}{!data.audit.length&&<p>Nenhum evento disponível neste histórico.</p>}</>}
  </>}</div></dialog>;
}
